-- Create contact_messages table
CREATE TABLE contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    read BOOLEAN DEFAULT FALSE
);

-- Add RLS (Row Level Security) policies
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;

-- Only allow authenticated users to read messages
CREATE POLICY "Allow authenticated users to read messages"
ON contact_messages
FOR SELECT
TO authenticated
USING (true);

-- Allow anyone to insert messages
CREATE POLICY "Allow anyone to insert messages"
ON contact_messages
FOR INSERT
TO anon
WITH CHECK (true);

-- Only allow authenticated users to update messages
CREATE POLICY "Allow authenticated users to update messages"
ON contact_messages
FOR UPDATE
TO authenticated
USING (true); 